feat(movies): add popups, sorting capability
mishalisovyi/react-gmp-app pull request #3
Opened 2022-06-07 20:22 UTC by mishalisovyi

2022-06-13 14:51 UTC, danyloburavlov requested changes

2022-06-13 14:51 UTC, danyloburavlov commented on src/common/hoc/ModalWindow/ModalWindow.tsx
> +  const primaryButtonElement = primaryButton.show
`useMemo` and also check other places.

2022-06-13 14:51 UTC, danyloburavlov commented on src/common/hoc/withPortalRendering/withPortalRendering.tsx
> +  return function renderPortal({ ...props }: Props) {
Nice!

2022-06-13 14:51 UTC, danyloburavlov commented on src/common/ui/ButtonPrimary/ButtonPrimary.tsx
> +  return <button type="button" className="button button--primary" onClick={onClick}>{text}</button>;
Make your components reusable. The only thing that really changes here is the class. You can create only 1 button and just send it 1 prop.

2022-06-13 14:51 UTC, danyloburavlov commented on src/common/ui/DropdownMenu/DropdownMenu.tsx
> +  const handleMenuOptionClick = useCallback(memoize((option: string) => {
Why additional memoize? If you want to avoid the problem you mentioned earlier just create 2 memoized functions and use one inside the other.

2022-06-13 14:51 UTC, danyloburavlov commented on src/common/ui/FilterSelectList/FilterSelectList.tsx
> +          return <option className={styles['control__option']} key={item.value} value={item.value}>{item.title}</option>;
I doubt `value` is purely unique.

2022-06-13 14:51 UTC, danyloburavlov commented on src/entities/movie/components/MoviesContainer/MoviesContainer.tsx
> +      const moviesData = await getList({ sortField });
It'd be better to make the actual call inside the hook and return `movies` and `loading`.

2022-06-13 14:51 UTC, danyloburavlov commented on src/entities/movie/components/MoviesFilterPanel/MoviesFilterPanel.tsx
> +  const handleSelectionChanged = (selectedValue: string) => {
You can just pass `onSort` on sort as a prop.

2022-06-13 15:44 UTC, mishalisovyi commented on src/common/hoc/ModalWindow/ModalWindow.tsx
> +  const primaryButtonElement = primaryButton.show
okay, will check

2022-06-13 15:45 UTC, mishalisovyi commented on src/common/hoc/withPortalRendering/withPortalRendering.tsx
> +  return function renderPortal({ ...props }: Props) {
Thanks)

2022-06-13 16:26 UTC, mishalisovyi commented on src/common/ui/ButtonPrimary/ButtonPrimary.tsx
> +  return <button type="button" className="button button--primary" onClick={onClick}>{text}</button>;
Good advice, thanks. Will rework it.

2022-06-13 16:52 UTC, mishalisovyi commented on src/common/ui/DropdownMenu/DropdownMenu.tsx
> +  const handleMenuOptionClick = useCallback(memoize((option: string) => {
I didn't manage to get it work as you suggested. 
Tried a lot of options...

These two are compiled at least but inner functions are not cached anyway. Each time outer function is executed, it creates new anonymous inner function. 

![image](https://user-images.githubusercontent.com/34865063/173402235-ad4e5cfe-c2e4-431b-9363-b6cdc77db253.png)
![image](https://user-images.githubusercontent.com/34865063/173402451-49a72ea7-b645-4cee-8e3d-fbcbbd6f32d1.png)

The problem is that inner function needs `tabIndex` parameter which can not be directly passed as regular parameter because in this way TS compiler argues that `handleTabClick` can not be used as click event handler.

Also I was thinking about putting `tabIndex` to deps array of `useCallback` wrapping inner function. But in this case we have kind of circular dependency because `setIndex` can not set this value and depends on it at the same time.

So, the best option I came up was to use `memoize` package. Maybe you can suggest how to organize it properly?

2022-06-13 17:21 UTC, mishalisovyi commented on src/common/ui/FilterSelectList/FilterSelectList.tsx
> +          return <option className={styles['control__option']} key={item.value} value={item.value}>{item.title}</option>;
Theoretically there shouldn't be any options with same values in select list. But I'll rewrite the way how this key is composed to make it more unique.

2022-06-13 17:31 UTC, mishalisovyi commented on src/entities/movie/components/MoviesContainer/MoviesContainer.tsx
> +      const moviesData = await getList({ sortField });
The task description says: "No need to implement real API calls. Only add pages with mocked data.". That's why I implemented it without actual HTTP call :)
Anyway I see that in home task 6 we'll have to link our frontend with backend, so this part will be reworked to make HTTP calls.

2022-06-13 17:49 UTC, mishalisovyi commented on src/entities/movie/components/MoviesFilterPanel/MoviesFilterPanel.tsx
> +  const handleSelectionChanged = (selectedValue: string) => {
I'll rework this in the next home task

2022-06-13 18:01 UTC, merged

2022-06-14 10:01 UTC, danyloburavlov commented on src/entities/movie/components/MoviesContainer/MoviesContainer.tsx
> +      const moviesData = await getList({ sortField });
I don't talk about real API calls. I suggest you compose your functionality more properly.